

;; Third Homework Set
;; CSc 335
;; Spring 2024


;; 1. Exercise 1.9 from A&S, with additional requirements
;
;; consider two procedures for adding two positive integers
;

(define (my-plus-version-1 a b)
  (if (= a 0)
      b
      (inc (my-plus-version-1 (dec a) b))))

(define (my-plus-version-2 a b)
  (if (= a 0)
      b
      (my-plus-version-2 (dec a) (inc b))))

;; where

(define (inc x) (+ x 1))

(define (dec x) (- x 1))



;; Using the substitution model, illustrate the process generated by each
;; procedure in evaluating (my-plus 4 5).  Are the processes recursive or
;; iterative?
;
;; Certify each procedure, using the appropriate technique, as determined
;; by your answer to the classification question above: for the recursive
;; procedure, give a proof based on the size of (one of) the arguments; for
;; the iterative procedure, give a proof which uses an invariant (which you
;; must first discover)


;; 2. Develop and certify iterative and recursive scheme functions to return the sum of the
;; digits within a non-negative integer.  For example, (sum-of-digits 345) is 12.


